-- Autoformat
return {}
-- return {
--     "stevearc/conform.nvim",
--     event = "BufWritePre",  -- Autoformat on save
--     keys = {
--         {
--             "<leader>f",
--             function()
--                 require("conform").format { async = true, lsp_format = "fallback" }
--             end,
--             mode = "",
--             desc = "[F]ormat buffer",
--         },
--     },
--     opts = {
--         notify_on_error = true,
--         format_on_save = function(bufnr)
--             -- Disable formatting for languages that don't have a well standardized coding style.
--             local disable_filetypes = { c = true, cpp = true }
--             if disable_filetypes[vim.bo[bufnr].filetype] then
--                 return nil
--             else
--                 return {
--                     timeout_ms = 500,
--                     lsp_format = "fallback",
--                 }
--             end
--         end,
--     },
-- }
